import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const BASE_URL = "https://www.ruralhomeguide.com";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: "Rural Home Guide — The Complete Guide to Rural Homeownership",
  description:
    "The complete guide to rural homeownership. Private wells, septic systems, propane, water rights, and everything in between. Real answers — without the jargon.",
  alternates: {
    canonical: BASE_URL,
  },
  openGraph: {
    title: "Rural Home Guide",
    description:
      "The complete guide to rural homeownership. Private wells, septic systems, propane, water rights, and everything in between.",
    url: BASE_URL,
    siteName: "Rural Home Guide",
    type: "website",
    locale: "en_US",
    // OG image is auto-generated by app/opengraph-image.tsx (Next.js edge runtime)
  },
  twitter: {
    card: "summary_large_image",
    title: "Rural Home Guide",
    description:
      "The complete guide to rural homeownership. Private wells, septic systems, propane, water rights, and everything in between.",
    // Twitter image auto-resolved from app/opengraph-image.tsx
  },
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
    other: [{ rel: "manifest", url: "/site.webmanifest" }],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
